name: Python linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint bandit
    - name: Run unit tests
      run: |
        python calc_room_size/test_main.py
    - name: Analysing the code for coding issues with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Analysing the code for security issues with bandit
      run: |
        bandit -c bandit.yaml $(git ls-files '*.py')


